## 시카고 Community Area Name

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [4]:
area_name = pd.read_csv('/content/chicago-community-areas.csv')

In [5]:
chicago = pd.read_csv('/content/drive/MyDrive/final_csv/chicago_final.csv')

In [6]:
area_name

,Community Area,1,2,3,4,5,6,7,8,9,...,68,69,70,71,72,73,74,75,76,77
0,name,Rogers Park,West Ridge,Uptown,Lincoln Square,North Center,Lake View,Lincoln Park,Near North Side,Edison Park,...,Englewood,Greater Grand Crossing,Ashburn,Auburn Gresham,Beverly,Washington Heights,Mount Greenwood,Morgan Park,O'Hare,Edgewater
1,population,54991,71942,56362,39493,31867,94368,64116,80484,11187,...,30654,32602,41081,48743,20034,26493,19093,22544,12756,56521
2,income,39482,47323,40324,57749,81524,70746,82707,76290,77678,...,19743,29663,62238,34767,83092,42053,80505,56886,49601,43331
3,requests,3204.8880725907,3906.3412193156,2164.0466981295,3827.2605271849,5307.9988703031,2742.2431332668,3408.6655437027,1717.6084687635,4754.6259050653,...,5459.646375673,6296.85295381,5599.4255251814,5785.446115344,6985.125287016,6641.7544256946,4357.6179751737,6264.1944641542,1552.9946691765,2564.8873869877
4,latinos,0.244,0.204,0.142,0.191,0.136,0.076,0.056,0.049,0.078,...,0.011,0.012,0.368,0.009,0.046,0.01,0.072,0.027,0.095,0.165
5,blacks,0.263,0.111,0.2,0.038,0.023,0.039,0.043,0.108,0.003,...,0.974,0.969,0.462,0.978,0.341,0.974,0.052,0.667,0.032,0.143
6,white,0.393,0.427,0.516,0.631,0.773,0.804,0.829,0.721,0.884,...,0.003,0.006,0.152,0.003,0.588,0.005,0.86,0.287,0.772,0.547
7,asian,0.064,0.225,0.114,0.111,0.045,0.06,0.051,0.101,0.024,...,0.001,0.001,0.007,0.001,0.006,0,0.007,0.004,0.083,0.116
8,other,0.036,0.032,0.028,0.029,0.022,0.021,0.021,0.02,0.012,...,0.011,0.013,0.011,0.009,0.019,0.012,0.01,0.014,0.019,0.029

In [7]:
# 전치 후, 기존의 행 인덱스를 새로운 열로 추가
area_name = area_name.T.reset_index()

In [8]:
# 기존 행 인덱스를 새로운 열로 추가했으므로, 인덱스를 재설정
area_name = area_name.rename(columns={'index': 'Original Index'})

In [9]:
# 첫 번째 행을 컬럼명으로 설정
area_name.columns = area_name.iloc[0]
area_name

,Community Area,name,population,income,requests,latinos,blacks,white,asian,other
0,Community Area,name,population,income,requests,latinos,blacks,white,asian,other
1,1,Rogers Park,54991,39482,3204.8880725907,0.244,0.263,0.393,0.064,0.036
2,2,West Ridge,71942,47323,3906.3412193156,0.204,0.111,0.427,0.225,0.032
3,3,Uptown,56362,40324,2164.0466981295,0.142,0.2,0.516,0.114,0.028
4,4,Lincoln Square,39493,57749,3827.2605271849,0.191,0.038,0.631,0.111,0.029
...,...,...,...,...,...,...,...,...,...,...
73,73,Washington Heights,26493,42053,6641.7544256946,0.01,0.974,0.005,0,0.012
74,74,Mount Greenwood,19093,80505,4357.6179751737,0.072,0.052,0.86,0.007,0.01
75,75,Morgan Park,22544,56886,6264.1944641542,0.027,0.667,0.287,0.004,0.014
76,76,O'Hare,12756,49601,1552.9946691765,0.095,0.032,0.772,0.083,0.019
77,77,Edgewater,56521,43331,2564.8873869877,0.165,0.143,0.547,0.116,0.029

In [10]:
area_name.to_csv("community_areas_final.csv", index=False, header=False)

In [11]:
chicago.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location', 'F_Date', 'Time'],
      dtype='object')

### 시카고 CommunityArea 번호 수정

* 시카고의 공식 Community Area는 0~76번
* 시카고 범죄 데이터의 Community Area는 0~77번
  -> 77번 데이터의 개수를 파악 후 제거 고려

In [12]:
chicago['Community Area'].unique()

array([61., 49., 50., 73., 29., 65., 59., 66., 23., 62., 67., 70., 10.,
       25., 43., 28., 22., 68., 30., 40., 19.,  3., 71., 42., 34., 63.,
       55., 35., 27., 48., 72., 69., 18., 15., 12.,  7., 52., 60., 58.,
       44., 24., 74.,  5., 56., 21.,  8., 32., 33., 38., 16., 26.,  1.,
       31., 41., 51.,  6., 46., 57., 77., 75.,  2., 53., 14., 39., 13.,
       17.,  4., 11., 54., 64.,  9., 20., 45., 76., 37., 47., 36.,  0.])

In [13]:
# 시카고 커뮤니티 area 의 실제 개수는 77
# 0이나 77이 누락 데이터인지 확인
print(len(chicago[chicago['Community Area'] == 77]))
print(len(chicago[chicago['Community Area'] == 0]))

78024
95

In [14]:
chicago.shape

(7836600, 24)

### CM 0번 제거 version

- 95개로 0.000012%의 작은 데이터 이므로 제거

In [17]:
# 'Community Area'가 0인 행 제거
chicago = chicago[chicago['Community Area'] != 0]

In [18]:
chicago['Community Area'].unique()

array([61., 49., 50., 73., 29., 65., 59., 66., 23., 62., 67., 70., 10.,
       25., 43., 28., 22., 68., 30., 40., 19.,  3., 71., 42., 34., 63.,
       55., 35., 27., 48., 72., 69., 18., 15., 12.,  7., 52., 60., 58.,
       44., 24., 74.,  5., 56., 21.,  8., 32., 33., 38., 16., 26.,  1.,
       31., 41., 51.,  6., 46., 57., 77., 75.,  2., 53., 14., 39., 13.,
       17.,  4., 11., 54., 64.,  9., 20., 45., 76., 37., 47., 36.])

In [19]:
chicago.shape

(7836505, 24)

In [22]:
area_name = area_name.iloc[1:,0:2]

In [23]:
area_name.head()

0 Community Area            name
1              1     Rogers Park
2              2      West Ridge
3              3          Uptown
4              4  Lincoln Square
5              5    North Center

In [29]:
area_name = area_name.rename(columns={'name' : 'ca_name'})

### chicago 데이터에 이름 결합

In [49]:
chicago['Community Area'] = chicago['Community Area'].astype(int)

In [52]:
# 'Community Area' 컬럼을 모두 문자열로 변환
chicago['Community Area'] = chicago['Community Area'].astype(str)
area_name['Community Area'] = area_name['Community Area'].astype(str)

In [53]:
chicago['Community Area'].dtype

dtype('O')

In [54]:
chicago['Community Area']

0          61
1          49
2          50
3          73
4          29
           ..
7836595    30
7836596    69
7836597    66
7836598    46
7836599    69
Name: Community Area, Length: 7836505, dtype: object

In [55]:
merge = pd.merge(chicago, area_name, how='left', on='Community Area')

In [56]:
merge.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location', 'F_Date', 'Time', 'ca_name'],
      dtype='object')

In [57]:
merge.head(1)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,F_Date,Time,ca_name
0,4676906,HM278933,2003-03-01 00:00:00,004XX W 42ND PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,...,1173974.0,1876757.0,2003.0,04/15/2016 08:55:02 AM,41.817229,-87.637328,"(41.817229156, -87.637328162)",2003-03-01,00:00:00,New City

In [58]:
merge[['Community Area', 'ca_name']]

        Community Area                 ca_name
0                   61                New City
1                   49                Roseland
2                   50                 Pullman
3                   73      Washington Heights
4                   29          North Lawndale
...                ...                     ...
7836500             30          South Lawndale
7836501             69  Greater Grand Crossing
7836502             66            Chicago Lawn
7836503             46           South Chicago
7836504             69  Greater Grand Crossing

[7836505 rows x 2 columns]

In [59]:
# 맞게 들어갔는지 확인
area_name[area_name['Community Area'] == '61']

0  Community Area   ca_name
61             61  New City

In [65]:
# community name 을 포함한 범죄 파일 저장
merge.to_csv("/content/drive/MyDrive/final_csv/chicago_with_cm.csv", index=False)

In [66]:
pd.read_csv('/content/drive/MyDrive/final_csv/chicago_with_cm.csv').head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,F_Date,Time,ca_name
0,4676906,HM278933,2003-03-01 00:00:00,004XX W 42ND PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,...,1173974.0,1876757.0,2003.0,04/15/2016 08:55:02 AM,41.817229,-87.637328,"(41.817229156, -87.637328162)",2003-03-01,00:00:00,New City
1,4677901,HM275615,2003-05-01 01:00:00,111XX S NORMAL AVE,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,...,1174948.0,1831051.0,2003.0,04/15/2016 08:55:02 AM,41.691785,-87.635116,"(41.691784636, -87.635115968)",2003-05-01,01:00:00,Roseland
2,4791194,HM403711,2001-01-01 11:00:00,114XX S ST LAWRENCE AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,True,...,1182247.0,1829375.0,2001.0,08/29/2006 03:46:28 AM,41.687020,-87.608445,"(41.687020002, -87.60844523)",2001-01-01,11:00:00,Pullman
3,4679521,HM216293,2003-03-15 00:00:00,090XX S RACINE AVE,5007,OTHER OFFENSE,OTHER WEAPONS VIOLATION,RESIDENCE PORCH/HALLWAY,False,False,...,1169911.0,1844832.0,2003.0,04/15/2016 08:55:02 AM,41.729712,-87.653159,"(41.729712374, -87.653158513)",2003-03-15,00:00:00,Washington Heights
4,4680124,HM282389,2003-01-01 00:00:00,009XX S SPAULDING AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,1154521.0,1895755.0,2003.0,04/15/2016 08:55:02 AM,41.869772,-87.708180,"(41.869772159, -87.708180162)",2003-01-01,00:00:00,North Lawndale