In [ ]:
import gdown

file_ids = {
    "Chicago_Crimes_2001_to_2004.csv": "1OzcB0ikBcADK7_C3A9iLLnx6zJIRobkZ",
    "Chicago_Crimes_2005_to_2007.csv": "1SlCjb42HWjkc8BdoJyWQAeVcznX2dcW2",
    "Chicago_Crimes_2008_to_2011.csv": "1leerrQTNFX2jvggdb_Oosf-Z1C60EL2b",
    "Chicago_Crimes_2012_to_2017.csv" : "1m4f7SGp7YLvxzAUAusQ4qQd1-dcIdPYw"
}

for filename, file_id in file_ids.items():
    url = f"https://drive.google.com/uc?export=download&id={file_id}"
    gdown.download(url, filename, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?export=download&id=1OzcB0ikBcADK7_C3A9iLLnx6zJIRobkZ
From (redirected): https://drive.google.com/uc?export=download&id=1OzcB0ikBcADK7_C3A9iLLnx6zJIRobkZ&confirm=t&uuid=155f6e2d-5a92-4911-9e3b-73b48b69ca90
To: /content/Chicago_Crimes_2001_to_2004.csv

  0%|          | 0.00/475M [00:00<?, ?B/s]
  1%|▏         | 6.82M/475M [00:00<00:11, 41.0MB/s]
  4%|▎         | 16.8M/475M [00:00<00:06, 67.8MB/s]
  8%|▊         | 36.2M/475M [00:00<00:04, 106MB/s]
 10%|▉         | 47.2M/475M [00:00<00:05, 81.9MB/s]
 15%|█▍        | 70.3M/475M [00:00<00:03, 122MB/s]
 18%|█▊        | 84.4M/475M [00:00<00:04, 94.3MB/s]
 20%|██        | 95.9M/475M [00:01<00:04, 87.0MB/s]
 22%|██▏       | 106M/475M [00:01<00:11, 32.4MB/s]
 28%|██▊       | 134M/475M [00:02<00:06, 56.8MB/s]
 34%|███▍      | 161M/475M [00:02<00:03, 84.7MB/s]
 38%|███▊      | 180M/475M [00:02<00:03, 87.3MB/s]
 41%|████      | 196M/475M [00:02<00:03, 92.4MB/s]
 44%|████▍     | 210M/475M [00:02<00:02, 88.5MB/s]
 49%|████▉     | 233M/475M [00:02<00:02, 104MB/s]
 52%|█████▏    | 246M/475M [00:03<00:02, 94.1MB/s]
 57%|█████▋    | 273M/475M [00:03<00:01, 114MB/s]
 60%|██████    | 286M/475M [00:03<00:01, 103MB/s]
 63%|██████▎   | 298M/475M [00:03<00:01, 98.7MB/s]
 68%|██████▊   | 322M/475M [00:03<00:01, 128MB/s]
 71%|███████   | 337M/475M [00:03<00:01, 91.3MB/s]
 76%|███████▌  | 361M/475M [00:04<00:00, 116MB/s]
 79%|███████▉  | 376M/475M [00:04<00:00, 112MB/s]
 84%|████████▍ | 399M/475M [00:04<00:00, 131MB/s]
 87%|████████▋ | 414M/475M [00:04<00:00, 106MB/s]
 92%|█████████▏| 438M/475M [00:04<00:00, 133MB/s]
 96%|█████████▌| 455M/475M [00:04<00:00, 105MB/s]
100%|██████████| 475M/475M [00:05<00:00, 95.0MB/s]
Downloading...
From (original): https://drive.google.com/uc?export=download&id=1SlCjb42HWjkc8BdoJyWQAeVcznX2dcW2
From (redirected): https://drive.google.com/uc?export=download&id=1SlCjb42HWjkc8BdoJyWQAeVcznX2dcW2&confirm=t&uuid=6be5bb3f-41d6-412a-b106-a9e51fe599f5
To: /content/Chicago_Crimes_2005_to_2007.csv

  0%|          | 0.00/471M [00:00<?, ?B/s]
  1%|▏         | 6.82M/471M [00:00<00:27, 16.7MB/s]
  3%|▎         | 13.1M/471M [00:00<00:19, 24.0MB/s]
  9%|▊         | 40.4M/471M [00:00<00:05, 82.4MB/s]
 12%|█▏        | 54.5M/471M [00:00<00:05, 81.5MB/s]
 15%|█▌        | 70.8M/471M [00:00<00:03, 100MB/s]
 18%|█▊        | 86.5M/471M [00:01<00:03, 108MB/s]
 22%|██▏       | 105M/471M [00:01<00:04, 84.2MB/s]
 27%|██▋       | 128M/471M [00:01<00:03, 111MB/s]
 31%|███       | 146M/471M [00:01<00:02, 124MB/s]
 35%|███▌      | 165M/471M [00:01<00:02, 140MB/s]
 39%|███▉      | 184M/471M [00:01<00:01, 152MB/s]
 43%|████▎     | 204M/471M [00:01<00:01, 164MB/s]
 48%|████▊     | 228M/471M [00:02<00:01, 182MB/s]
 53%|█████▎    | 247M/471M [00:02<00:01, 186MB/s]
 58%|█████▊    | 271M/471M [00:02<00:01, 179MB/s]
 62%|██████▏   | 290M/471M [00:02<00:01, 135MB/s]
 66%|██████▌   | 310M/471M [00:02<00:01, 149MB/s]
 69%|██████▉   | 327M/471M [00:02<00:01, 140MB/s]
 73%|███████▎  | 343M/471M [00:02<00:01, 112MB/s]
 77%|███████▋  | 361M/471M [00:03<00:00, 126MB/s]
 80%|████████  | 378M/471M [00:03<00:00, 135MB/s]
 84%|████████▍ | 397M/471M [00:03<00:00, 149MB/s]
 88%|████████▊ | 415M/471M [00:03<00:00, 155MB/s]
 92%|█████████▏| 431M/471M [00:03<00:00, 157MB/s]
 95%|█████████▌| 448M/471M [00:03<00:00, 101MB/s]
100%|██████████| 471M/471M [00:03<00:00, 120MB/s]
Downloading...
From (original): https://drive.google.com/uc?export=download&id=1leerrQTNFX2jvggdb_Oosf-Z1C60EL2b
From (redirected): https://drive.google.com/uc?export=download&id=1leerrQTNFX2jvggdb_Oosf-Z1C60EL2b&confirm=t&uuid=8c92eade-6224-468a-be7c-9d286ad3ea43
To: /content/Chicago_Crimes_2008_to_2011.csv

  0%|          | 0.00/678M [00:00<?, ?B/s]
  1%|          | 4.72M/678M [00:00<00:21, 31.5MB/s]
  1%|▏         | 8.91M/678M [00:00<00:25, 26.1MB/s]
  5%|▌         | 34.1M/678M [00:00<00:08, 80.4MB/s]
  7%|▋         | 50.3M/678M [00:00<00:06, 102MB/s]
  9%|▉         | 61.9M/678M [00:00<00:09, 66.5MB/s]
 12%|█▏        | 78.1M/678M [00:01<00:10, 55.6MB/s]
 16%|█▌        | 105M/678M [00:01<00:08, 64.6MB/s]
 19%|█▉        | 132M/678M [00:01<00:05, 92.0MB/s]
 21%|██▏       | 145M/678M [00:02<00:07, 72.3MB/s]
 26%|██▌       | 176M/678M [00:02<00:04, 107MB/s]
 30%|██▉       | 202M/678M [00:02<00:04, 115MB/s]
 32%|███▏      | 218M/678M [00:02<00:04, 103MB/s]
 35%|███▌      | 240M/678M [00:02<00:04, 105MB/s]
 38%|███▊      | 261M/678M [00:02<00:03, 108MB/s]
 42%|████▏     | 282M/678M [00:03<00:03, 101MB/s]
 44%|████▍     | 300M/678M [00:03<00:03, 115MB/s]
 47%|████▋     | 317M/678M [00:03<00:03, 97.4MB/s]
 51%|█████     | 347M/678M [00:03<00:02, 133MB/s]
 54%|█████▍    | 365M/678M [00:03<00:02, 143MB/s]
 57%|█████▋    | 384M/678M [00:03<00:01, 152MB/s]
 60%|█████▉    | 405M/678M [00:04<00:02, 117MB/s]
 64%|██████▍   | 433M/678M [00:04<00:01, 149MB/s]
 67%|██████▋   | 452M/678M [00:04<00:02, 104MB/s]
 70%|███████   | 474M/678M [00:04<00:02, 101MB/s]
 75%|███████▍  | 505M/678M [00:04<00:01, 135MB/s]
 77%|███████▋  | 524M/678M [00:05<00:01, 108MB/s]
 81%|████████  | 546M/678M [00:05<00:01, 123MB/s]
 83%|████████▎ | 562M/678M [00:05<00:01, 101MB/s]
 87%|████████▋ | 592M/678M [00:05<00:00, 124MB/s]
 91%|█████████ | 617M/678M [00:05<00:00, 146MB/s]
 94%|█████████▎| 634M/678M [00:06<00:00, 117MB/s]
100%|██████████| 678M/678M [00:06<00:00, 109MB/s]
Downloading...
From (original): https://drive.google.com/uc?export=download&id=1m4f7SGp7YLvxzAUAusQ4qQd1-dcIdPYw
From (redirected): https://drive.google.com/uc?export=download&id=1m4f7SGp7YLvxzAUAusQ4qQd1-dcIdPYw&confirm=t&uuid=dc51e630-ce0d-4d3f-b600-6eafb1b8e3e1
To: /content/Chicago_Crimes_2012_to_2017.csv

  0%|          | 0.00/367M [00:00<?, ?B/s]
  1%|▏         | 4.72M/367M [00:00<00:14, 25.6MB/s]
  5%|▍         | 17.3M/367M [00:00<00:07, 49.5MB/s]
 13%|█▎        | 46.7M/367M [00:00<00:02, 125MB/s]
 17%|█▋        | 62.9M/367M [00:00<00:03, 89.9MB/s]
 21%|██▏       | 78.1M/367M [00:00<00:02, 104MB/s]
 25%|██▌       | 91.8M/367M [00:01<00:03, 87.7MB/s]
 28%|██▊       | 103M/367M [00:01<00:03, 73.5MB/s]
 34%|███▍      | 126M/367M [00:01<00:02, 100MB/s]
 38%|███▊      | 138M/367M [00:01<00:02, 80.9MB/s]
 45%|████▍     | 165M/367M [00:01<00:01, 115MB/s]
 49%|████▉     | 180M/367M [00:02<00:02, 89.8MB/s]
 55%|█████▌    | 202M/367M [00:02<00:01, 107MB/s]
 59%|█████▉    | 217M/367M [00:02<00:01, 101MB/s]
 66%|██████▌   | 242M/367M [00:02<00:01, 115MB/s]
 69%|██████▉   | 255M/367M [00:02<00:01, 104MB/s]
 76%|███████▌  | 277M/367M [00:02<00:00, 112MB/s]
 80%|████████  | 294M/367M [00:03<00:00, 105MB/s]
 89%|████████▉ | 328M/367M [00:03<00:00, 129MB/s]
 94%|█████████▍| 344M/367M [00:03<00:00, 120MB/s]
100%|██████████| 367M/367M [00:03<00:00, 103MB/s]

In [ ]:
import pandas as pd

df1 = pd.read_csv("Chicago_Crimes_2001_to_2004.csv", on_bad_lines='skip', low_memory=False)
df2 = pd.read_csv("Chicago_Crimes_2005_to_2007.csv", on_bad_lines='skip', low_memory=False)
df3 = pd.read_csv("Chicago_Crimes_2008_to_2011.csv", on_bad_lines='skip', low_memory=False)
df4 = pd.read_csv("Chicago_Crimes_2012_to_2017.csv", on_bad_lines='skip', low_memory=False)

In [ ]:
a = df1.shape[0]
b = df2.shape[0]
c = df3.shape[0]
d = df4.shape[0]

a+b+c+d

7941282

In [ ]:
df = pd.concat([df1, df2, df3, df4])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7941282 entries, 0 to 1456713
Data columns (total 23 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  object
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  float64
 14  Community Area        float64
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          object
 18  Year                  float64
 19  Updated On            object
 20  Latitude              object
 21  Longitude             float64
 22  Location              object
dtypes: bool(2), float64(6), int64(3), object(12)
memory usage: 1.3+ GB

In [ ]:
# Y coordinate에 있는 잘못된 형태의 데이터 탐색(숫자만 있어야 하는데 그렇지 않은 것이 있음)
import numpy as np

df['Y num'] = pd.to_numeric(df['Y Coordinate'], errors='coerce')
error = df[df['Y num'].isna() & df['Y Coordinate'].notna()]

error

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Y num
1602847,3629582,1423259,G139165,03/10/2001 11:30:00 PM,035XX S FEDERAL ST,1340,CRIMINAL DAMAGE,TO STATE SUP PROP,CHA PARKING LOT/GROUNDS,True,...,NaN,14,1176246.0,18 08:55:02 AM,41.789832,-87.672973835,"(41.789832136, -87.672973835)",NaN,NaN,NaN

In [ ]:
df['Y num'] = pd.to_numeric(df['Y Coordinate'], errors='coerce')
error = df[df['Y num'].isna() & df['Y Coordinate'].notna()]

error

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Y num
1602847,3629582,1423259,G139165,03/10/2001 11:30:00 PM,035XX S FEDERAL ST,1340,CRIMINAL DAMAGE,TO STATE SUP PROP,CHA PARKING LOT/GROUNDS,True,...,NaN,14,1176246.0,18 08:55:02 AM,41.789832,-87.672973835,"(41.789832136, -87.672973835)",NaN,NaN,NaN

In [ ]:
df.iloc[1602847, 17]

'18 08:55:02 AM'

In [ ]:
df.iat[1602847, 17] = np.nan if df.iat[1602847, 17] == '18 08:55:02 AM' else df.iat[1602847, 17]
df.iat[1602847, 18] = 2001
df.iat[1602847, 20] = 41.789832136
df.iat[1602847, 21] = -87.672973835

df.iat[1602847, 19] = np.nan

In [ ]:
df['Latitude'] = df['Latitude'].astype('float')
df['Year'] = df['Year'].astype('int')
df['Date'] = pd.to_datetime(df['Date'])
df['Y Coordinate'] = df['Y Coordinate'].astype('float')
df['Updated On'] = pd.to_datetime(df['Updated On'])

df.info()

<ipython-input-31-7be029f6c4cc>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])
<ipython-input-31-7be029f6c4cc>:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Updated On'] = pd.to_datetime(df['Updated On'])

<class 'pandas.core.frame.DataFrame'>
Index: 7941282 entries, 0 to 1456713
Data columns (total 24 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  datetime64[ns]
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  float64
 14  Community Area        float64
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          float64
 18  Year                  int64
 19  Updated On            datetime64[ns]
 20  Latitude              float64
 21  Longitude             float64
 22  Location              object
 23  Y num                 float64
dtypes: bool(2), datetime64[ns](2), float64(8), int64(4), object(8)
memory usage: 1.4+ GB

In [ ]:
df.isnull().sum()

Unnamed: 0                   0
ID                           0
Case Number                  7
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1990
Arrest                       0
Domestic                     0
Beat                         0
District                    91
Ward                    700224
Community Area          702091
FBI Code                     0
X Coordinate            105573
Y Coordinate            105574
Year                         0
Updated On                   1
Latitude                105573
Longitude               105573
Location                105574
Y num                   105574
dtype: int64

- ID: 해당 기록의 고유 식별자.
- Case Number: 사건의 고유 번호(시카고 경찰서 기록부 번호, RD 번호).
- Date: 사건이 발생한 날짜.
- Block: 사건이 발생한 주소(블록 단위).
- IUCR: 일리노이 범죄 보고 코드(Illinois Uniform Crime Reporting Code).
- Primary Type: IUCR 코드의 주요 범죄 유형.
- Description: IUCR 코드의 세부 범죄 유형(Primary Type의 하위 범주).
- Location Description: 사건이 발생한 장소의 설명.
- Arrest: 체포 여부.
- Domestic: 해당 사건이 일리노이 가정 폭력법에 따라 가정폭력 관련 사건인지 여부.
- Beat: 사건이 발생한 경찰 순찰 구역(가장 작은 경찰 행정 단위).
- District: 사건이 발생한 경찰서 관할 구역.
- Ward: 사건이 발생한 시의회 선거구(워드).
- Community Area: 사건이 발생한 커뮤니티 지역(시카고에는 총 77개의 커뮤니티 지역이 있음).
- FBI Code: FBI 국가 사건 기반 보고 시스템(NIBRS) 기준의 범죄 분류 코드.
- X Coordinate: 사건이 발생한 위치의 X 좌표(State Plane Illinois East NAD 1983 기준).
- Y Coordinate: 사건이 발생한 위치의 Y 좌표(State Plane Illinois East NAD 1983 기준).
- Year: 사건이 발생한 연도.
- Updated On: 해당 기록이 마지막으로 업데이트된 날짜 및 시간.
- Latitude: 사건이 발생한 위치의 위도(개인 정보 보호를 위해 실제 위치에서 약간 이동됨).
- Longitude: 사건이 발생한 위치의 경도(개인 정보 보호를 위해 실제 위치에서 약간 이동됨).
- Location: 사건이 발생한 위치를 지도 제작 및 기타 지리적 분석이 가능하도록 저장한 좌표(개인 정보 보호를 위해 실제 위치에서 약간 이동됨).

In [ ]:
df_s = df.copy()
df_s = df_s.sort_values(by='Block')
df_s

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Y num
23841,831012,9391364,HW522925,2013-11-05 22:26:00,0000X I94/EXIT 12,2027,NARCOTICS,POSS: CRACK,VEHICLE NON-COMMERCIAL,False,...,NaN,18,NaN,NaN,2013,2015-08-17 15:03:40,NaN,NaN,NaN,NaN
375467,3915792,1783308,G592093,2001-10-02 23:00:00,0000X E 100 PL,2014,NARCOTICS,MANU/DELIVER: HEROIN (WHITE),STREET,True,...,NaN,18,1178667.0,1838318.0,2001,2015-08-17 15:03:40,41.711643,-87.621280,"(41.711642766, -87.621280337)",1838318.0
205046,3745370,1570487,G332330,2001-06-08 14:56:13,0000X E 100 PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,STREET,False,...,NaN,04B,1178490.0,1838313.0,2001,2015-08-17 15:03:40,41.711633,-87.621929,"(41.71163306, -87.621928703)",1838313.0
341969,3882294,1741813,G550395,2001-09-13 16:40:00,0000X E 100 PL,0820,THEFT,$500 AND UNDER,STREET,False,...,NaN,06,1178488.0,1838393.0,2001,2015-08-17 15:03:40,41.711853,-87.621934,"(41.711852636, -87.621933607)",1838393.0
530088,4130151,1976769,HH170203,2002-02-06 07:00:00,0000X E 100 PL,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,...,NaN,26,1178454.0,1838352.0,2002,2016-04-15 08:55:02,41.711741,-87.622059,"(41.711740897, -87.622059364)",1838352.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23782,830818,9306074,HW429063,2013-08-29 13:40:00,175XX W WINSTON COURT,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,VEHICLE NON-COMMERCIAL,False,...,NaN,18,NaN,NaN,2013,2015-08-17 15:03:40,NaN,NaN,NaN,NaN
1151305,815606,6479762,HP507951,2008-08-11 19:50:00,XX UNKNOWN,1822,NARCOTICS,MANU/DEL:CANNABIS OVER 10 GMS,APARTMENT,False,...,NaN,18,NaN,NaN,2008,2015-08-17 15:03:40,NaN,NaN,NaN,NaN
1160867,828355,8220140,HT453754,2008-01-01 00:00:00,XX UNKNOWN,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,...,NaN,06,NaN,NaN,2008,2015-08-17 15:03:40,NaN,NaN,NaN,NaN
3810,815606,6479762,HP507951,2008-08-11 19:50:00,XX UNKNOWN,1822,NARCOTICS,MANU/DEL:CANNABIS OVER 10 GMS,APARTMENT,False,...,NaN,18,NaN,NaN,2008,2015-08-17 15:03:40,NaN,NaN,NaN,NaN
13372,828355,8220140,HT453754,2008-01-01 00:00:00,XX UNKNOWN,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,...,NaN,06,NaN,NaN,2008,2015-08-17 15:03:40,NaN,NaN,NaN,NaN

In [ ]:
# 결측치 채우기
# 결측치 없는 유일한 주소 정보인 block을 기준으로 결측치를 채우기
# 평균으로 하면 잘못 적은 데이터에 의해 정보가 왜곡될 수 있으므로 최빈값 사용

df_s['Latitude'] = df_s['Latitude'].fillna(df_s.groupby('Block')['Latitude'].transform(lambda x: x.mode()[0] if not x.mode().empty else x))
df_s['Longitude'] = df_s['Longitude'].fillna(df_s.groupby('Block')['Longitude'].transform(lambda x: x.mode()[0] if not x.mode().empty else x))

df_s['Ward'] = df_s['Ward'].fillna(df_s.groupby('Block')['Ward'].transform(lambda x: x.mode()[0] if not x.mode().empty else x))
df_s['Community Area'] = df_s['Community Area'].fillna(df_s.groupby('Block')['Community Area'].transform(lambda x: x.mode()[0] if not x.mode().empty else x))

df_s['X Coordinate'] = df_s['X Coordinate'].fillna(df_s.groupby('Block')['X Coordinate'].transform(lambda x: x.mode()[0] if not x.mode().empty else x))
df_s['Y Coordinate'] = df_s['Y Coordinate'].fillna(df_s.groupby('Block')['Y Coordinate'].transform(lambda x: x.mode()[0] if not x.mode().empty else x))

df_s['Location'] = df_s['Location'].fillna('( '+ df_s['Latitude'].astype('str') + ', ' + df_s['Longitude'].astype('str') + ')')

df_s.isna().sum()

  1%|          | 11.0M/2.16G [1:13:06<238:14:23, 2.51kB/s]

Unnamed: 0                   0
ID                           0
Case Number                  7
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1990
Arrest                       0
Domestic                     0
Beat                         0
District                    91
Ward                    499682
Community Area          500196
FBI Code                     0
X Coordinate              2872
Y Coordinate              2872
Year                         0
Updated On                   1
Latitude                  2872
Longitude                 2872
Location                     0
Y num                   105574
dtype: int64

In [ ]:
import geopandas as gpd

gdf = gpd.read_file("Boundaries - Wards (2023-)_20250328.geojson")

In [ ]:
import geopandas as gpd
from shapely.geometry import Point

wards_gdf = gpd.read_file("Boundaries - Wards (2023-)_20250328.geojson")

df_s["Latitude"] = df_s["Latitude"].astype(float)
df_s["Longitude"] = df_s["Longitude"].astype(float)

# crime_df = pd.read_csv("chicago_crime_data.csv")

df_s["geometry"] = df_s.apply(lambda row: Point(row["Longitude"], row["Latitude"]), axis=1)

crime_gdf = gpd.GeoDataFrame(df_s, geometry="geometry", crs="EPSG:4326")

crime_gdf = gpd.sjoin(crime_gdf, wards_gdf[["ward", "geometry"]], how="left", predicate="within")

df_s["Ward"].fillna(crime_gdf["ward"], inplace=True)

df_s.info()

<ipython-input-36-7e4408c13c3a>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_s["Ward"].fillna(crime_gdf["ward"], inplace=True)
<ipython-input-36-7e4408c13c3a>:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9' '9' '9' ... '10' '10' '10']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_s["Ward"].fillna(crime_gdf["ward"], inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 7941282 entries, 23841 to 13372
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  datetime64[ns]
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  object
 14  Community Area        float64
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          float64
 18  Year                  int64
 19  Updated On            datetime64[ns]
 20  Latitude              float64
 21  Longitude             float64
 22  Location              object
 23  Y num                 float64
 24  geometry              object
dtypes: bool(2), datetime64[ns](2), float64(7), int64(4), object(10)
memory usage: 1.4+ GB

In [ ]:
# cond = (df_s['Ward'] == np.nan)

# df_s[cond].shape

df_s['Ward'] = df_s['Ward'].astype('float')
df_s.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7941282 entries, 23841 to 13372
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  datetime64[ns]
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  float64
 14  Community Area        float64
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          float64
 18  Year                  int64
 19  Updated On            datetime64[ns]
 20  Latitude              float64
 21  Longitude             float64
 22  Location              object
 23  Y num                 float64
 24  geometry              object
dtypes: bool(2), datetime64[ns](2), float64(8), int64(4), object(9)
memory usage: 1.4+ GB

In [ ]:
geo_data = gpd.read_file("CommAreas_20250328.geojson")

df_s["geometry"] = df_s.apply(lambda row: Point(row["Longitude"], row["Latitude"]), axis=1)

gdf = gpd.GeoDataFrame(df_s, geometry='geometry', crs="EPSG:4326")

gdf = gdf.sjoin(geo_data[['geometry', 'area_num_1']], how="left", predicate="within")

df_s['Community Area'] = df_s['Community Area'].fillna(gdf['area_num_1'])

In [ ]:
df_s.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7941282 entries, 23841 to 13372
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  datetime64[ns]
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  float64
 14  Community Area        object
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          float64
 18  Year                  int64
 19  Updated On            datetime64[ns]
 20  Latitude              float64
 21  Longitude             float64
 22  Location              object
 23  Y num                 float64
 24  geometry              object
dtypes: bool(2), datetime64[ns](2), float64(7), int64(4), object(10)
memory usage: 1.4+ GB

In [ ]:
df_s.isna().sum()

# 결측치가 70만 개에서 2820개로 감소

Unnamed: 0                   0
ID                           0
Case Number                  7
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1990
Arrest                       0
Domestic                     0
Beat                         0
District                    91
Ward                      2780
Community Area            2821
FBI Code                     0
X Coordinate              2872
Y Coordinate              2872
Year                         0
Updated On                   1
Latitude                  2872
Longitude                 2872
Location                     0
Y num                   105574
geometry                     0
dtype: int64

In [ ]:
import gdown

file_ids = {"data_filling.csv": "1-2rEeagVMf1zWbmuJ0hDOkB_FC0cGfEn"}

for filename, file_id in file_ids.items():
    url = f"https://drive.google.com/uc?export=download&id={file_id}"
    gdown.download(url, filename, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?export=download&id=1-2rEeagVMf1zWbmuJ0hDOkB_FC0cGfEn
From (redirected): https://drive.google.com/uc?export=download&id=1-2rEeagVMf1zWbmuJ0hDOkB_FC0cGfEn&confirm=t&uuid=ef4559bc-fc67-4006-93f5-37bbf938805d
To: /content/data_filling.csv
  7%|▋         | 141M/2.16G [00:02<00:32, 62.9MB/s]

KeyboardInterrupt:

In [ ]:
import pandas as pd

df_t = pd.read_csv("data_filling.csv", on_bad_lines='skip', low_memory=False)

In [ ]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7941282 entries, 0 to 7941281
Data columns (total 23 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  object
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  float64
 14  Community Area        object
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          float64
 18  Year                  float64
 19  Updated On            object
 20  Latitude              float64
 21  Longitude             float64
 22  Location              object
dtypes: bool(2), float64(7), int64(3), object(11)
memory usage: 1.3+ GB

In [ ]:
df_t.isna().sum()

Unnamed: 0                 0
ID                         0
Case Number                7
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1990
Arrest                     0
Domestic                   0
Beat                       0
District                  91
Ward                    2922
Community Area          2995
FBI Code                   0
X Coordinate            2872
Y Coordinate            2872
Year                       0
Updated On                 0
Latitude                2872
Longitude               2872
Location                2872
dtype: int64