In [1]:
# 모듈 불러오기
import pandas as pd
import numpy as np

In [3]:
# 데이터 불러오기
df = pd.read_csv("data/merge_data.csv", low_memory=False)

In [5]:
# 결측치 확인
df.isnull().sum()

Unnamed: 0                   0
ID                           0
Case Number                  7
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1990
Arrest                       0
Domestic                     0
Beat                         0
District                    91
Ward                    700224
Community Area          702091
FBI Code                     0
X Coordinate            105573
Y Coordinate            105573
Year                         0
Updated On                   0
Latitude                105573
Longitude               105574
Location                105574
dtype: int64

In [7]:
# 각 Block 별 Latitude, Longitude의 최빈값(Mode)으로 결측치 채우기
df['Latitude'] = df.groupby('Block')['Latitude'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)
df['Longitude'] = df.groupby('Block')['Longitude'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)

# Block 별로 Location의 최빈값을 구하고 결측치를 채우기
df['Location'] = df.groupby('Block')['Location'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)

# Block별로 X Coordinate와 Y Coordinate의 최빈값을 사용하여 결측치 채우기
df['X Coordinate'] = df.groupby('Block')['X Coordinate'].transform(lambda x: x.mode()[0] if not x.mode().empty else x.mean())
df['Y Coordinate'] = df.groupby('Block')['Y Coordinate'].transform(lambda x: x.mode()[0] if not x.mode().empty else x.mean())

In [8]:
# 결측치 확인
df.isnull().sum()

Unnamed: 0                   0
ID                           0
Case Number                  7
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1990
Arrest                       0
Domestic                     0
Beat                         0
District                    91
Ward                    700224
Community Area          702091
FBI Code                     0
X Coordinate              2872
Y Coordinate              2872
Year                         0
Updated On                   0
Latitude                  2872
Longitude                 2872
Location                  2872
dtype: int64

In [11]:
# Latitude와 Longitude가 모두 NULL인 행
df[df['Latitude'].isnull() | df['Longitude'].isnull()]

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
1919,820249,6960102,HR345309,11/10/2002 05:00:00 PM,020XX S TAN CT,0266,CRIM SEXUAL ASSAULT,PREDATORY,APARTMENT,True,...,25.0,34.0,02,NaN,NaN,2002.0,08/17/2015 03:03:40 PM,NaN,NaN,NaN
3377,885828,1917641,HH100677,01/01/2002 12:01:00 AM,022XX W 109 ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,...,NaN,NaN,14,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3413,885864,1923055,HH104372,01/01/2002 10:00:00 AM,022XX W 106 ST,1330,CRIMINAL TRESPASS,TO LAND,RESIDENCE,False,...,NaN,NaN,26,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3469,885920,1926069,HH110484,01/06/2002 06:25:00 PM,035XX E 103 ST,0460,BATTERY,SIMPLE,STREET,True,...,NaN,NaN,08B,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3626,886077,1936982,HH122834,01/12/2002 07:00:00 PM,005XX W 128 PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,...,NaN,NaN,26,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7935885,6230772,10814243,JA113330,01/11/2017 12:00:00 AM,025XX W Chicago Ave,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,RESTAURANT,False,...,1.0,24.0,14,NaN,NaN,2017.0,01/18/2017 03:50:44 PM,NaN,NaN,NaN
7935886,6230773,10814244,JA113530,01/11/2017 01:40:00 PM,020XX W Jackson Blvd,0810,THEFT,OVER $500,APARTMENT,False,...,2.0,28.0,06,NaN,NaN,2017.0,01/18/2017 03:50:44 PM,NaN,NaN,NaN
7937002,6231892,10815280,JA114700,01/13/2017 02:54:00 PM,046XX S DAN RYAN XPRS IB,3710,INTERFERENCE WITH PUBLIC OFFICER,RESIST/OBSTRUCT/DISARM OFFICER,STREET,False,...,3.0,37.0,24,NaN,NaN,2017.0,01/20/2017 03:50:54 PM,NaN,NaN,NaN
7938873,6233770,10817906,JA118304,01/15/2017 03:00:00 AM,041XX N Troy St,0810,THEFT,OVER $500,STREET,False,...,33.0,16.0,06,NaN,NaN,2017.0,01/22/2017 03:47:43 PM,NaN,NaN,NaN
7941182,6236081,10827200,JA128245,01/03/2017 09:00:00 AM,016XX W Superior St,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,...,1.0,24.0,11,NaN,NaN,2017.0,01/25/2017 03:54:12 PM,NaN,NaN,NaN

- 2803에 대한 진실 : 2001~2004 데이터 파일만 활용했을 가능성 높음

In [14]:
num_unique_blocks = df[df['Latitude'].isnull() | df['Longitude'].isnull()]['Block'].nunique()
print(num_unique_blocks)

1177

In [16]:
df[df['Block'] == '011XX W 119TH ST']

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
283,116971,4973044,HM575112,05/23/2004 10:51:00 AM,011XX W 119TH ST,0840,THEFT,FINANCIAL ID THEFT: OVER $300,FACTORY/MANUFACTURING BUILDING,False,...,34.0,53.0,06,1170896.0,1825886.0,2004.0,08/17/2015 03:03:40 PM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
1277774,4881560,2992493,HJ694140,10/15/2003 06:30:00 AM,011XX W 119TH ST,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT/GARAGE(NON.RESID.),False,...,34.0,53.0,14,1170896.0,1825886.0,2003.0,08/17/2015 03:03:40 PM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
1513872,116971,4973044,HM575112,05/23/2004 10:51:00 AM,011XX W 119TH ST,0840,THEFT,FINANCIAL ID THEFT: OVER $300,FACTORY/MANUFACTURING BUILDING,False,...,34.0,53.0,06,1170896.0,1825886.0,2004.0,08/17/2015 03:03:40 PM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3220662,768773,5968678,HN763354,12/15/2007 12:00:00 PM,011XX W 119TH ST,0610,BURGLARY,FORCIBLE ENTRY,WAREHOUSE,False,...,34.0,53.0,05,1170896.0,1825886.0,2007.0,04/15/2016 08:55:02 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3332742,5606417,3882020,HL256124,03/26/2005 05:00:00 AM,011XX W 119TH ST,0610,BURGLARY,FORCIBLE ENTRY,FACTORY/MANUFACTURING BUILDING,False,...,34.0,53.0,05,1170896.0,1825886.0,2005.0,04/15/2016 08:55:02 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3419493,5694805,4043006,HL392404,06/01/2005 02:30:00 PM,011XX W 119TH ST,0890,THEFT,FROM BUILDING,VACANT LOT/LAND,False,...,34.0,53.0,06,1170896.0,1825886.0,2005.0,04/15/2016 08:55:02 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3479617,5755745,4157409,HL492068,07/18/2005 01:35:00 AM,011XX W 119TH ST,0810,THEFT,OVER $500,OTHER,False,...,34.0,53.0,06,1170896.0,1825886.0,2005.0,04/15/2016 08:55:02 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3500401,5776769,4195700,HL450567,06/28/2005 10:09:49 PM,011XX W 119TH ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,STREET,True,...,34.0,53.0,18,1170896.0,1825886.0,2005.0,04/15/2016 08:55:02 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3508495,5784965,4211485,HL528077,08/02/2005 04:00:00 PM,011XX W 119TH ST,1330,CRIMINAL TRESPASS,TO LAND,FACTORY/MANUFACTURING BUILDING,False,...,34.0,53.0,26,1170896.0,1825886.0,2005.0,04/15/2016 08:55:02 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
3860022,938587,6090297,HP186490,02/21/2008 09:40:00 AM,011XX W 119TH ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,OTHER,False,...,34.0,53.0,08B,1170896.0,1825886.0,2008.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
5007517,938587,6090297,HP186490,02/21/2008 09:40:00 AM,011XX W 119TH ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,OTHER,False,...,34.0,53.0,08B,1170896.0,1825886.0,2008.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
6345397,2276469,8217520,HT451787,08/16/2011 11:53:00 PM,011XX W 119TH ST,0320,ROBBERY,STRONGARM - NO WEAPON,CTA BUS,False,...,34.0,53.0,03,1170896.0,1825886.0,2011.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
6442946,2374018,8369448,HT602481,11/23/2011 12:00:00 PM,011XX W 119TH ST,0850,THEFT,ATTEMPT THEFT,FACTORY/MANUFACTURING BUILDING,False,...,34.0,53.0,06,1170896.0,1825886.0,2011.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
6450679,2381751,8381525,HT614233,11/30/2011 08:05:00 PM,011XX W 119TH ST,0610,BURGLARY,FORCIBLE ENTRY,FACTORY/MANUFACTURING BUILDING,True,...,34.0,53.0,05,1170896.0,1825886.0,2011.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
6771242,2620811,8758901,HV433721,08/16/2012 08:55:00 PM,011XX W 119TH ST,2027,NARCOTICS,POSS: CRACK,STREET,True,...,34.0,53.0,18,1170896.0,1825886.0,2012.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
6936627,2786782,9024290,HW171728,02/26/2013 09:22:00 PM,011XX W 119TH ST,502R,OTHER OFFENSE,VEHICLE TITLE/REG OFFENSE,VEHICLE NON-COMMERCIAL,True,...,34.0,53.0,26,1170896.0,1825886.0,2013.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
7085267,2935756,9264549,HW409169,08/02/2013 10:15:00 PM,011XX W 119TH ST,0820,THEFT,$500 AND UNDER,OTHER,False,...,34.0,53.0,06,1170896.0,1825886.0,2013.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
7145219,2995835,9361549,HW504536,10/23/2013 04:04:00 PM,011XX W 119TH ST,2027,NARCOTICS,POSS: CRACK,STREET,True,...,34.0,53.0,18,1170896.0,1825886.0,2013.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
7222860,3073612,9493588,HX147439,02/11/2014 11:30:00 AM,011XX W 119TH ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,PARKING LOT/GARAGE(NON.RESID.),False,...,34.0,53.0,07,1170896.0,1825886.0,2014.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
7339023,3189837,9694915,HX345431,07/14/2014 10:02:00 PM,011XX W 119TH ST,2024,NARCOTICS,POSS: HEROIN(WHITE),SIDEWALK,True,...,34.0,53.0,18,1170896.0,1825886.0,2014.0,02/04/2016 06:33:39 AM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"
7692392,3544466,10388430,HZ124830,01/22/2016 03:20:00 PM,011XX W 119TH ST,0560,ASSAULT,SIMPLE,OTHER,False,...,34.0,53.0,08A,1170896.0,1825886.0,2016.0,01/29/2016 03:52:43 PM,41.677700202,-87.650101,"(41.677700202, -87.650100809)"

In [160]:
# 'community_area'가 1인 행 필터링
community_area_1 = df[df['Community Area'] == 1.0]

# 'Latitude'와 'Longitude' 값 출력
print(community_area_1[['Latitude', 'Longitude']])

             Latitude  Longitude
305      42.000982305 -87.660726
346      42.012769161 -87.666942
537       42.00067123 -87.670464
688      42.021993365 -87.674246
742      42.009200477 -87.661081
...               ...        ...
7940543   42.02025525 -87.670728
7940830  42.020271587 -87.673086
7940945   42.01980733 -87.668248
7941060  42.010087614 -87.680709
7941217  42.017114262 -87.684369

[111408 rows x 2 columns]

In [18]:
# 각 community_area 별로 Latitude, Longitude의 최빈값(Mode) 계산
mode_values = df.groupby('Community Area')[['Latitude', 'Longitude', 'Location', 'X Coordinate', 'Y Coordinate']].agg(lambda x: x.mode()[0])

# 결측치를 각 Community Area 별로 최빈값으로 채우기
for community in mode_values.index:
    df.loc[(df['Community Area'] == community) & (df['Latitude'].isna()), 'Latitude'] = mode_values.loc[community, 'Latitude']
    df.loc[(df['Community Area'] == community) & (df['Longitude'].isna()), 'Longitude'] = mode_values.loc[community, 'Longitude']
    df.loc[(df['Community Area'] == community) & (df['Location'].isna()), 'Location'] = mode_values.loc[community, 'Location']
    df.loc[(df['Community Area'] == community) & (df['X Coordinate'].isna()), 'X Coordinate'] = mode_values.loc[community, 'X Coordinate']
    df.loc[(df['Community Area'] == community) & (df['Y Coordinate'].isna()), 'Y Coordinate'] = mode_values.loc[community, 'Y Coordinate']

# 결측치가 채워졌는지 확인
print(df[['Community Area', 'Latitude', 'Longitude', 'Location','X Coordinate', 'Y Coordinate']].isna().sum())

Community Area    702091
Latitude            2487
Longitude           2487
Location            2487
X Coordinate        2487
Y Coordinate        2487
dtype: int64

In [20]:
# 각 community_area 별로 Latitude, Longitude의 최빈값(Mode) 계산
mode_values = df.groupby('Ward')[['Latitude', 'Longitude', 'Location', 'X Coordinate', 'Y Coordinate']].agg(lambda x: x.mode()[0])

# 결측치를 각 Community Area 별로 최빈값으로 채우기
for community in mode_values.index:
    df.loc[(df['Ward'] == community) & (df['Latitude'].isna()), 'Latitude'] = mode_values.loc[community, 'Latitude']
    df.loc[(df['Ward'] == community) & (df['Longitude'].isna()), 'Longitude'] = mode_values.loc[community, 'Longitude']
    df.loc[(df['Ward'] == community) & (df['Location'].isna()), 'Location'] = mode_values.loc[community, 'Location']
    df.loc[(df['Ward'] == community) & (df['X Coordinate'].isna()), 'X Coordinate'] = mode_values.loc[community, 'X Coordinate']
    df.loc[(df['Ward'] == community) & (df['Y Coordinate'].isna()), 'Y Coordinate'] = mode_values.loc[community, 'Y Coordinate']

# 결측치가 채워졌는지 확인
print(df[['Ward', 'Latitude', 'Longitude', 'Location','X Coordinate', 'Y Coordinate']].isna().sum())

Ward            700224
Latitude          2411
Longitude         2411
Location          2411
X Coordinate      2411
Y Coordinate      2411
dtype: int64

In [30]:
import geopandas as gpd

# 시카고 Ward GeoJSON 불러오기 (구글 드라이브 경로)
gdf_wards = gpd.read_file("data/chicago-wards.geojson") # 맞게 변환

# 좌표계 확인 및 설정
if gdf_wards.crs is None:
    gdf_wards.set_crs(epsg=4326, inplace=True)
else:
    gdf_wards = gdf_wards.to_crs(epsg=4326)

import geopandas as gpd
from shapely.geometry import Point

# 꼭 필요한 열만 추출
df_coords = df.loc[
    df['Latitude'].notnull() & df['Longitude'].notnull() & df['Ward'].isnull(),
    ['Latitude', 'Longitude']
].copy()

# 벡터 연산으로 Point 생성
geometry = gpd.points_from_xy(df_coords['Longitude'].astype(float), df_coords['Latitude'].astype(float))

# GeoDataFrame 생성
gdf_coords = gpd.GeoDataFrame(df_coords, geometry=geometry, crs='EPSG:4326')

gdf_wards = gpd.read_file("data/chicago-wards.geojson")
gdf_wards = gdf_wards.to_crs(epsg=4326)

# Spatial join
joined = gpd.sjoin(gdf_coords, gdf_wards, how='left', predicate='within')

# ward 컬럼명 자동 감지
ward_col_name = [col for col in joined.columns if 'ward' in col.lower()][0]

# 인덱스 정렬 맞춰서 채우기
df.loc[joined.index, 'Ward'] = joined[ward_col_name].values

In [32]:
# 시카고 커뮤니티 지역 GeoJSON 로드
gdf_community = gpd.read_file("data/chicago-community-areas.geojson") # 맞게 수정
gdf_community = gdf_community.to_crs(epsg=4326)

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

# 커뮤니티 지역 GeoJSON 로드
gdf_community = gpd.read_file("data/chicago-community-areas.geojson") # 맞게 수정
gdf_community = gdf_community.to_crs(epsg=4326)

# 결측치 있는 위경도 데이터만 필터링
df_missing_comm = df.loc[
    df['Community Area'].isnull() &
    df['Latitude'].notnull() &
    df['Longitude'].notnull(),
    ['Latitude', 'Longitude']
].copy()

# 인덱스 보존
df_missing_comm['orig_index'] = df_missing_comm.index

# 💡 데이터가 많으니 5000개 단위로 나눠서 Spatial Join
batch_size = 5000
filled_area = []

for i in range(0, len(df_missing_comm), batch_size):
    batch = df_missing_comm.iloc[i:i+batch_size].copy()
    # Point 객체 생성 (벡터화)
    geometry = gpd.points_from_xy(batch['Longitude'].astype(float), batch['Latitude'].astype(float))
    gdf_batch = gpd.GeoDataFrame(batch, geometry=geometry, crs='EPSG:4326')

    # Spatial Join
    joined = gpd.sjoin(gdf_batch, gdf_community, how='left', predicate='within')

    # community area 컬럼명 자동 탐색
    comm_col = [col for col in joined.columns if 'community' in col.lower() or 'area' in col.lower()][0]

    # 결과 저장
    filled_area.append(joined[['orig_index', comm_col]])

# 결과 통합
area_result = pd.concat(filled_area)

# 원본 df에 반영
df.loc[area_result['orig_index'], 'Community Area'] = area_result[comm_col].values

/var/folders/1k/kfyrfwj51r7_zts1bndgk56c0000gn/T/ipykernel_27315/510052135.py:47: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['SOUTH SHORE' 'NORTH LAWNDALE' 'HUMBOLDT PARK' ... 'CHATHAM' nan nan]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[area_result['orig_index'], 'Community Area'] = area_result[comm_col].values

In [34]:
df.isnull().sum()

Unnamed: 0                 0
ID                         0
Case Number                7
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1990
Arrest                     0
Domestic                   0
Beat                       0
District                  91
Ward                    2935
Community Area          3198
FBI Code                   0
X Coordinate            2411
Y Coordinate            2411
Year                       0
Updated On                 0
Latitude                2411
Longitude               2411
Location                2411
dtype: int64

In [38]:
df.to_csv('test.csv')

In [52]:
# Latitude와 Longitude가 모두 NULL인 행
df[df['Ward'].isnull() | df['Community Area'].isnull()]

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
2602,827954,808,G259321,05/06/2001 01:30:00 AM,020XX W 55 ST,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,True,...,NaN,NaN,01A,0.0,0.0,2001.0,08/17/2015 03:03:40 PM,36.619446395,-91.686566,"(36.619446395, -91.686565684)"
3377,885828,1917641,HH100677,01/01/2002 12:01:00 AM,022XX W 109 ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,...,NaN,NaN,14,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3413,885864,1923055,HH104372,01/01/2002 10:00:00 AM,022XX W 106 ST,1330,CRIMINAL TRESPASS,TO LAND,RESIDENCE,False,...,NaN,NaN,26,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3469,885920,1926069,HH110484,01/06/2002 06:25:00 PM,035XX E 103 ST,0460,BATTERY,SIMPLE,STREET,True,...,NaN,NaN,08B,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3626,886077,1936982,HH122834,01/12/2002 07:00:00 PM,005XX W 128 PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,...,NaN,NaN,26,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6956105,2806335,9058946,HW203626,03/22/2013 09:00:00 PM,056XX N FAIRVIEW AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,DRIVEWAY - RESIDENTIAL,False,...,NaN,0.0,14,1119936.0,1936755.0,2013.0,02/04/2016 06:33:39 AM,41.982902855,-87.834278,"(41.982902855, -87.834278328)"
7199570,3050270,9451711,HX105019,12/19/2013 01:35:00 PM,065XX N MANNHEIM RD,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,...,NaN,0.0,07,1106264.0,1941887.0,2013.0,02/04/2016 06:33:39 AM,41.997193305,-87.884464,"(41.997193305, -87.884463632)"
7223777,3074531,9494842,HX149198,02/11/2014 10:30:00 PM,056XX N FAIRVIEW AVE,0810,THEFT,OVER $500,RESIDENTIAL YARD (FRONT/BACK),False,...,NaN,0.0,06,1119936.0,1936755.0,2014.0,02/04/2016 06:33:39 AM,41.982902855,-87.834278,"(41.982902855, -87.834278328)"
7417972,3268787,9827727,HX464897,10/12/2014 02:30:00 PM,065XX N MANNHEIM RD,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,...,NaN,0.0,14,1106264.0,1941887.0,2014.0,02/04/2016 06:33:39 AM,41.997193305,-87.884464,"(41.997193305, -87.884463632)"
7621606,3473478,10266945,HY454232,10/08/2015 10:00:00 AM,056XX N FAIRVIEW AVE,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,RESIDENCE-GARAGE,False,...,NaN,0.0,14,1119936.0,1936755.0,2015.0,10/15/2015 03:57:16 PM,41.982902855,-87.834278,"(41.982902855, -87.834278328)"

In [44]:
df[df.duplicated()]
df = df.drop_duplicates()

In [46]:
df.isnull().sum()

Unnamed: 0                 0
ID                         0
Case Number                4
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1968
Arrest                     0
Domestic                   0
Beat                       0
District                  49
Ward                    2567
Community Area          2806
FBI Code                   0
X Coordinate            2111
Y Coordinate            2111
Year                       0
Updated On                 0
Latitude                2111
Longitude               2111
Location                2111
dtype: int64

In [50]:
df2 = pd.read_csv('test.csv', low_memory=False)

In [62]:
# 각 Block 별 Latitude, Longitude의 최빈값(Mode)으로 결측치 채우기

df['Community Area'] = df['Community Area'].astype(str)
df['Ward'] = df.groupby('Block')['Ward'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)
df['Community Area'] = df.groupby('Block')['Community Area'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)

In [58]:
df.isnull().sum()

Unnamed: 0                 0
ID                         0
Case Number                4
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1968
Arrest                     0
Domestic                   0
Beat                       0
District                  49
Ward                    2267
Community Area             0
FBI Code                   0
X Coordinate            2111
Y Coordinate            2111
Year                       0
Updated On                 0
Latitude                2111
Longitude               2111
Location                2111
dtype: int64

In [64]:
df_with_strings = df[df['Community Area'].astype(str).str.isalpha()]

In [66]:
df_with_strings

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
1507,815017,642,G013102,01/07/2001 12:48:00 AM,007XX E 79 ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,...,6.0,CHATHAM,01A,1182846.0,1852758.0,2001.0,08/17/2015 03:03:40 PM,41.75117194,-87.605529,"(41.75117194, -87.605528747)"
1537,815300,645,G019063,01/09/2001 09:34:00 PM,010XX W 59 ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,...,16.0,ENGLEWOOD,01A,1170281.0,1865647.0,2001.0,08/17/2015 03:03:40 PM,41.786823398,-87.651198,"(41.786823398, -87.65119848)"
1570,815792,650,G023235,01/11/2001 06:46:00 PM,101XX S LASALLE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,...,9.0,ROSELAND,01A,1177058.0,1837772.0,2001.0,08/17/2015 03:03:40 PM,41.710180828,-87.627189,"(41.710180828, -87.627189271)"
1580,815881,651,G023235,01/11/2001 09:10:00 PM,101XX S LASALLE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,...,9.0,ROSELAND,01A,1177058.0,1837772.0,2001.0,08/17/2015 03:03:40 PM,41.710180828,-87.627189,"(41.710180828, -87.627189271)"
1632,816617,660,G032650,01/16/2001 09:00:00 AM,003XX W 81 ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,...,17.0,CHATHAM,01A,1175528.0,1851241.0,2001.0,08/17/2015 03:03:40 PM,41.747175846,-87.632391,"(41.747175846, -87.632390699)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7929842,6224716,10808901,JA107216,01/02/2017 09:00:00 PM,004XX W PERSHING RD,0810,THEFT,OVER $500,OTHER,False,...,11.0,BRIDGEPORT,06,1173691.0,1879063.0,2017.0,01/09/2017 03:46:53 PM,41.823667594,-87.638297,"(41.823667594, -87.638296724)"
7935028,6229915,10811826,JA111230,01/10/2017 09:23:00 PM,035XX S DEARBORN ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,...,3.0,DOUGLAS,08B,1176461.0,1881310.0,2017.0,01/17/2017 03:59:06 PM,41.829667334,-87.628068,"(41.829667334, -87.628068132)"
7938314,6233211,10822541,JA123311,12/03/2016 10:00:00 AM,004XX W PERSHING RD,1206,DECEPTIVE PRACTICE,"THEFT BY LESSEE,MOTOR VEH",COMMERCIAL / BUSINESS OFFICE,False,...,11.0,BRIDGEPORT,11,1173691.0,1879063.0,2016.0,01/21/2017 03:48:36 PM,41.823667594,-87.638297,"(41.823667594, -87.638296724)"
7938316,6233213,10822547,JA123312,12/09/2016 10:00:00 PM,004XX W PERSHING RD,1206,DECEPTIVE PRACTICE,"THEFT BY LESSEE,MOTOR VEH",COMMERCIAL / BUSINESS OFFICE,False,...,11.0,BRIDGEPORT,11,1173691.0,1879063.0,2016.0,01/21/2017 03:48:36 PM,41.823667594,-87.638297,"(41.823667594, -87.638296724)"
7939583,6234480,10819985,JA120432,01/16/2017 07:00:00 AM,035XX S FEDERAL ST,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,...,3.0,DOUGLAS,05,1176246.0,1881288.0,2017.0,01/23/2017 03:52:03 PM,41.829611625,-87.628828,"(41.829611625, -87.628828268)"

In [68]:
df_with_strings2 = df[df['Ward'].astype(str).str.isalpha()]

In [70]:
df_with_strings2

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
2602,827954,808,G259321,05/06/2001 01:30:00 AM,020XX W 55 ST,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,True,...,NaN,nan,01A,0.0,0.0,2001.0,08/17/2015 03:03:40 PM,36.619446395,-91.686566,"(36.619446395, -91.686565684)"
3377,885828,1917641,HH100677,01/01/2002 12:01:00 AM,022XX W 109 ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,...,NaN,nan,14,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3413,885864,1923055,HH104372,01/01/2002 10:00:00 AM,022XX W 106 ST,1330,CRIMINAL TRESPASS,TO LAND,RESIDENCE,False,...,NaN,nan,26,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3469,885920,1926069,HH110484,01/06/2002 06:25:00 PM,035XX E 103 ST,0460,BATTERY,SIMPLE,STREET,True,...,NaN,nan,08B,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
3626,886077,1936982,HH122834,01/12/2002 07:00:00 PM,005XX W 128 PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,...,NaN,nan,26,NaN,NaN,2002.0,02/04/2016 06:33:39 AM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6956105,2806335,9058946,HW203626,03/22/2013 09:00:00 PM,056XX N FAIRVIEW AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,DRIVEWAY - RESIDENTIAL,False,...,NaN,10.0,14,1119936.0,1936755.0,2013.0,02/04/2016 06:33:39 AM,41.982902855,-87.834278,"(41.982902855, -87.834278328)"
7199570,3050270,9451711,HX105019,12/19/2013 01:35:00 PM,065XX N MANNHEIM RD,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,...,NaN,0.0,07,1106264.0,1941887.0,2013.0,02/04/2016 06:33:39 AM,41.997193305,-87.884464,"(41.997193305, -87.884463632)"
7223777,3074531,9494842,HX149198,02/11/2014 10:30:00 PM,056XX N FAIRVIEW AVE,0810,THEFT,OVER $500,RESIDENTIAL YARD (FRONT/BACK),False,...,NaN,10.0,06,1119936.0,1936755.0,2014.0,02/04/2016 06:33:39 AM,41.982902855,-87.834278,"(41.982902855, -87.834278328)"
7417972,3268787,9827727,HX464897,10/12/2014 02:30:00 PM,065XX N MANNHEIM RD,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,...,NaN,0.0,14,1106264.0,1941887.0,2014.0,02/04/2016 06:33:39 AM,41.997193305,-87.884464,"(41.997193305, -87.884463632)"
7621606,3473478,10266945,HY454232,10/08/2015 10:00:00 AM,056XX N FAIRVIEW AVE,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,RESIDENCE-GARAGE,False,...,NaN,10.0,14,1119936.0,1936755.0,2015.0,10/15/2015 03:57:16 PM,41.982902855,-87.834278,"(41.982902855, -87.834278328)"

In [72]:
# 데이터 불러오기
df = pd.read_csv("data/merge_data.csv", low_memory=False)

In [74]:
# 각 Block 별 Latitude, Longitude의 최빈값(Mode)으로 결측치 채우기
df['Latitude'] = df.groupby('Block')['Latitude'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)
df['Longitude'] = df.groupby('Block')['Longitude'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)

# Block 별로 Location의 최빈값을 구하고 결측치를 채우기
df['Location'] = df.groupby('Block')['Location'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)

# Block별로 X Coordinate와 Y Coordinate의 최빈값을 사용하여 결측치 채우기
df['X Coordinate'] = df.groupby('Block')['X Coordinate'].transform(lambda x: x.mode()[0] if not x.mode().empty else x.mean())
df['Y Coordinate'] = df.groupby('Block')['Y Coordinate'].transform(lambda x: x.mode()[0] if not x.mode().empty else x.mean())

In [76]:
# 각 Block 별 Latitude, Longitude의 최빈값(Mode)으로 결측치 채우기
df['Community Area'] = df['Community Area'].astype(str)
df['Ward'] = df.groupby('Block')['Ward'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)
df['Community Area'] = df.groupby('Block')['Community Area'].transform(lambda x: x.mode()[0] if not x.mode().empty else x)

In [78]:
df.isnull().sum()

Unnamed: 0                   0
ID                           0
Case Number                  7
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1990
Arrest                       0
Domestic                     0
Beat                         0
District                    91
Ward                    499682
Community Area               0
FBI Code                     0
X Coordinate              2872
Y Coordinate              2872
Year                         0
Updated On                   0
Latitude                  2872
Longitude                 2872
Location                  2872
dtype: int64

In [84]:
import geopandas as gpd

# 시카고 Ward GeoJSON 불러오기 (구글 드라이브 경로)
gdf_wards = gpd.read_file("data/chicago-wards.geojson") # 맞게 변환

# 좌표계 확인 및 설정
if gdf_wards.crs is None:
    gdf_wards.set_crs(epsg=4326, inplace=True)
else:
    gdf_wards = gdf_wards.to_crs(epsg=4326)

import geopandas as gpd
from shapely.geometry import Point

# 꼭 필요한 열만 추출
df_coords = df.loc[
    df['Latitude'].notnull() & df['Longitude'].notnull() & df['Ward'].isnull(),
    ['Latitude', 'Longitude']
].copy()

# 벡터 연산으로 Point 생성
geometry = gpd.points_from_xy(df_coords['Longitude'].astype(float), df_coords['Latitude'].astype(float))

# GeoDataFrame 생성
gdf_coords = gpd.GeoDataFrame(df_coords, geometry=geometry, crs='EPSG:4326')

gdf_wards = gpd.read_file("data/chicago-wards.geojson")
gdf_wards = gdf_wards.to_crs(epsg=4326)

# Spatial join
joined = gpd.sjoin(gdf_coords, gdf_wards, how='left', predicate='within')

# ward 컬럼명 자동 감지
ward_col_name = [col for col in joined.columns if 'ward' in col.lower()][0]

# 인덱스 정렬 맞춰서 채우기
df.loc[joined.index, 'Ward'] = joined[ward_col_name].values

In [86]:
df.isnull().sum()

Unnamed: 0                 0
ID                         0
Case Number                7
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1990
Arrest                     0
Domestic                   0
Beat                       0
District                  91
Ward                    2587
Community Area             0
FBI Code                   0
X Coordinate            2872
Y Coordinate            2872
Year                       0
Updated On                 0
Latitude                2872
Longitude               2872
Location                2872
dtype: int64

In [88]:
# 각 community_area 별로 Latitude, Longitude의 최빈값(Mode) 계산
mode_values = df.groupby('Community Area')[['Latitude', 'Longitude', 'Location', 'X Coordinate', 'Y Coordinate']].agg(lambda x: x.mode()[0])

# 결측치를 각 Community Area 별로 최빈값으로 채우기
for community in mode_values.index:
    df.loc[(df['Community Area'] == community) & (df['Latitude'].isna()), 'Latitude'] = mode_values.loc[community, 'Latitude']
    df.loc[(df['Community Area'] == community) & (df['Longitude'].isna()), 'Longitude'] = mode_values.loc[community, 'Longitude']
    df.loc[(df['Community Area'] == community) & (df['Location'].isna()), 'Location'] = mode_values.loc[community, 'Location']
    df.loc[(df['Community Area'] == community) & (df['X Coordinate'].isna()), 'X Coordinate'] = mode_values.loc[community, 'X Coordinate']
    df.loc[(df['Community Area'] == community) & (df['Y Coordinate'].isna()), 'Y Coordinate'] = mode_values.loc[community, 'Y Coordinate']

# 결측치가 채워졌는지 확인
print(df[['Community Area', 'Latitude', 'Longitude', 'Location','X Coordinate', 'Y Coordinate']].isna().sum())

# 각 community_area 별로 Latitude, Longitude의 최빈값(Mode) 계산
mode_values = df.groupby('Ward')[['Latitude', 'Longitude', 'Location', 'X Coordinate', 'Y Coordinate']].agg(lambda x: x.mode()[0])

# 결측치를 각 Community Area 별로 최빈값으로 채우기
for community in mode_values.index:
    df.loc[(df['Ward'] == community) & (df['Latitude'].isna()), 'Latitude'] = mode_values.loc[community, 'Latitude']
    df.loc[(df['Ward'] == community) & (df['Longitude'].isna()), 'Longitude'] = mode_values.loc[community, 'Longitude']
    df.loc[(df['Ward'] == community) & (df['Location'].isna()), 'Location'] = mode_values.loc[community, 'Location']
    df.loc[(df['Ward'] == community) & (df['X Coordinate'].isna()), 'X Coordinate'] = mode_values.loc[community, 'X Coordinate']
    df.loc[(df['Ward'] == community) & (df['Y Coordinate'].isna()), 'Y Coordinate'] = mode_values.loc[community, 'Y Coordinate']

# 결측치가 채워졌는지 확인
print(df[['Ward', 'Latitude', 'Longitude', 'Location','X Coordinate', 'Y Coordinate']].isna().sum())

Community Area    0
Latitude          0
Longitude         0
Location          0
X Coordinate      0
Y Coordinate      0
dtype: int64
Ward            2587
Latitude           0
Longitude          0
Location           0
X Coordinate       0
Y Coordinate       0
dtype: int64

In [92]:
df.isnull().sum()

Unnamed: 0                 0
ID                         0
Case Number                7
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1990
Arrest                     0
Domestic                   0
Beat                       0
District                  91
Ward                    2587
Community Area             0
FBI Code                   0
X Coordinate               0
Y Coordinate               0
Year                       0
Updated On                 0
Latitude                   0
Longitude                  0
Location                   0
dtype: int64

In [96]:
df_with_strings3 = df[df['Community Area'].astype(str).str.isalpha()]

In [98]:
df_with_strings3

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
1332,808956,1954658,HH143979,01/23/2002 05:30:00 PM,071XX S EAST END AV,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,True,...,7.0,nan,02,1188808.0,1858180.0,2002.0,08/06/2016 03:49:51 PM,41.765911951,-87.583820,"(41.765911951, -87.583819655)"
1450,814436,636,G008548,01/04/2001 10:30:00 PM,035XX W 12 PL,0110,HOMICIDE,FIRST DEGREE MURDER,BASEMENT,True,...,24.0,nan,01A,1153015.0,1894102.0,2001.0,08/17/2015 03:03:40 PM,41.865266107,-87.713753,"(41.865266107, -87.713752956)"
1457,814500,637,G005960,01/06/2001 10:35:00 AM,014XX N HARDING ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,...,26.0,nan,01A,1149782.0,1909379.0,2001.0,08/17/2015 03:03:40 PM,41.907251262,-87.725224,"(41.907251262, -87.725224066)"
1468,814582,638,G008793,01/05/2001 04:22:00 PM,016XX W 80 ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,...,21.0,nan,01A,1166980.0,1851625.0,2001.0,08/17/2015 03:03:40 PM,41.748416411,-87.663702,"(41.748416411, -87.663701982)"
1507,815017,642,G013102,01/07/2001 12:48:00 AM,007XX E 79 ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,...,6.0,nan,01A,1182846.0,1852758.0,2001.0,08/17/2015 03:03:40 PM,41.75117194,-87.605529,"(41.75117194, -87.605528747)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7938314,6233211,10822541,JA123311,12/03/2016 10:00:00 AM,004XX W PERSHING RD,1206,DECEPTIVE PRACTICE,"THEFT BY LESSEE,MOTOR VEH",COMMERCIAL / BUSINESS OFFICE,False,...,11.0,nan,11,1173691.0,1879063.0,2016.0,01/21/2017 03:48:36 PM,41.823667594,-87.638297,"(41.823667594, -87.638296724)"
7938316,6233213,10822547,JA123312,12/09/2016 10:00:00 PM,004XX W PERSHING RD,1206,DECEPTIVE PRACTICE,"THEFT BY LESSEE,MOTOR VEH",COMMERCIAL / BUSINESS OFFICE,False,...,11.0,nan,11,1173691.0,1879063.0,2016.0,01/21/2017 03:48:36 PM,41.823667594,-87.638297,"(41.823667594, -87.638296724)"
7939583,6234480,10819985,JA120432,01/16/2017 07:00:00 AM,035XX S FEDERAL ST,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,...,3.0,nan,05,1176246.0,1881288.0,2017.0,01/23/2017 03:52:03 PM,41.829611625,-87.628828,"(41.829611625, -87.628828268)"
7940243,6235140,10819807,JA120228,01/17/2017 01:00:00 PM,032XX W MONROE ST,0453,BATTERY,AGGRAVATED PO: OTHER DANG WEAP,"SCHOOL, PUBLIC, BUILDING",False,...,28.0,nan,04B,1154551.0,1899349.0,2017.0,01/24/2017 03:55:11 PM,41.879633871,-87.707974,"(41.879633871, -87.707973888)"
7940609,6235507,10820028,JA120457,01/18/2017 10:50:00 AM,012XX W HARRISON ST,0890,THEFT,FROM BUILDING,OTHER,False,...,2.0,nan,06,1168041.0,1897531.0,2017.0,01/25/2017 03:54:12 PM,41.874364727,-87.658493,"(41.874364727, -87.658493167)"

In [100]:
df_with_strings4 = df[df['Latitude'].astype(str).str.isalpha()]

In [102]:
df_with_strings4

Empty DataFrame
Columns: [Unnamed: 0, ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 23 columns]